"""Localized strings for Joan HTML generated by html_generator (pl, en, de, fr, es, nl, cs)."""

from __future__ import annotations

from datetime import date

SUPPORTED_LANGS = frozenset({"pl", "en", "de", "fr", "es", "nl", "cs"})


def normalize_lang(lang: str | None) -> str:
    code = (lang or "en").lower().split("-", 1)[0]
    return code if code in SUPPORTED_LANGS else "en"


# --- Calendar: long day + month names (long date headers) ---
_DAY_LONG: dict[str, list[str]] = {
    "en": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "pl": ["Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"],
    "de": ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
    "fr": ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
    "es": ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"],
    "nl": ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"],
    "cs": ["pondělí", "úterý", "středa", "čtvrtek", "pátek", "sobota", "neděle"],
}

_MONTH_LONG: dict[str, list[str]] = {
    "en": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "pl": ["styczeń", "luty", "marzec", "kwiecień", "maj", "czerwiec", "lipiec", "sierpień", "wrzesień", "październik", "listopad", "grudzień"],
    "de": ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
    "fr": ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
    "es": ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
    "nl": ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"],
    "cs": ["leden", "únor", "březen", "duben", "květen", "červen", "červenec", "srpen", "září", "říjen", "listopad", "prosinec"],
}

# --- Short weekday abbreviations (grids, weather strip) ---
DAY_ABBR: dict[str, list[str]] = {
    "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "pl": ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "Nd"],
    "de": ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    "fr": ["lun", "mar", "mer", "jeu", "ven", "sam", "dim"],
    "es": ["lun", "mar", "mié", "jue", "vie", "sáb", "dom"],
    "nl": ["ma", "di", "wo", "do", "vr", "za", "zo"],
    "cs": ["po", "út", "st", "čt", "pá", "so", "ne"],
}

# Energy donut header: Polish uses DD.MM; others use "Mon DD Mon HH:MM"
DAY_ABBR_ENERGY_PL: list[str] = ["Pon", "Wt", "Sr", "Czw", "Pt", "Sob", "Nd"]


def format_long_date(d: date, lang: str) -> str:
    L = normalize_lang(lang)
    days = _DAY_LONG[L]
    months = _MONTH_LONG[L]
    if L == "pl":
        return f"{days[d.weekday()]}, {d.day} {months[d.month - 1]}"
    if L == "en":
        return f"{days[d.weekday()]}, {d.day} {months[d.month - 1]}"
    # fr/es/de/nl/cs: lowercase weekday + day month (common EU style)
    return f"{days[d.weekday()]}, {d.day} {months[d.month - 1]}"


def month_title(year: int, month: int, lang: str) -> str:
    L = normalize_lang(lang)
    mname = _MONTH_LONG[L][month - 1]
    if L == "pl":
        return f"{mname.capitalize()} {year}"
    if L == "en":
        return f"{mname} {year}"
    return f"{mname.capitalize()} {year}"


def day_abbr_list(lang: str) -> list[str]:
    L = normalize_lang(lang)
    return list(DAY_ABBR[L])


def day_abbr_for_energy_header(lang: str) -> list[str]:
    """Short labels for energy panel clock line."""
    if normalize_lang(lang) == "pl":
        return list(DAY_ABBR_ENERGY_PL)
    return list(DAY_ABBR[normalize_lang(lang)])


def format_energy_header_datetime(now_local, lang: str) -> str:
    """Human-readable date+time line on e-ink energy donut."""
    L = normalize_lang(lang)
    names = day_abbr_for_energy_header(L)
    t = now_local.strftime("%H:%M")
    if L == "pl":
        return f"{names[now_local.weekday()]} {now_local.day:02d}.{now_local.month:02d} {t}"
    if L == "en":
        return f"{names[now_local.weekday()]} {now_local.strftime('%d %b')} {t}"
    return f"{names[now_local.weekday()]} {now_local.day:02d}.{now_local.month:02d} {t}"


# --- Flat UI strings ---
_STR: dict[str, dict[str, str]] = {
    "en": {
        "todo_no_tasks": "No tasks on the list",
        "todo_no_description": "No description",
        "rss_failed": "Failed to load RSS feed",
        "rss_prev": "Previous",
        "rss_next": "Next",
        "rss_page": "Page",
        "rss_no_title": "No title",
        "energy_title": "Energy Panel",
        "energy_live": "Live Power",
        "energy_solar": "Solar",
        "energy_import": "Grid Import",
        "energy_export": "Grid Export",
        "energy_consumption": "Consumption",
        "energy_net": "Net Balance",
        "energy_self": "Self-Suf.",
        "crypto_title": "Crypto",
        "crypto_updated": "Updated",
        "crypto_no_chart": "No chart data",
        "fx_default_title": "Exchange Rates",
        "fx_no_hist": "No hist.",
        "cal_no_events": "No events on this day",
        "cal_no_title": "No title",
        "cal_title": "Calendar",
        "cal_monthly_title": "Monthly Calendar",
        "weather_no_forecast": "No forecast",
        "weather_title": "Weather",
        "weather_feels": "Feels like",
        "weather_wind": "Wind",
        "weather_pressure": "Pressure",
        "weather_humidity": "Humidity",
        "weather_no_daily": "No daily forecast data.",
        "weather_graph_err": "Error generating graph",
        "forecast_24h": "24h Forecast",
    },
    "pl": {
        "todo_no_tasks": "Brak zadań na liście",
        "todo_no_description": "Brak opisu",
        "rss_failed": "Nie udało się wczytać kanału RSS",
        "rss_prev": "Wstecz",
        "rss_next": "Dalej",
        "rss_page": "Strona",
        "rss_no_title": "Brak tytułu",
        "energy_title": "Panel Energetyczny",
        "energy_live": "Moc bieżąca",
        "energy_solar": "Produkcja PV",
        "energy_import": "Pobór z sieci",
        "energy_export": "Eksport do sieci",
        "energy_consumption": "Zużycie",
        "energy_net": "Bilans netto",
        "energy_self": "Autarkia",
        "crypto_title": "Kryptowaluty",
        "crypto_updated": "Aktualizacja",
        "crypto_no_chart": "Brak wykresu",
        "fx_default_title": "Kursy walut",
        "fx_no_hist": "Brak hist.",
        "cal_no_events": "Brak wydarzeń tego dnia",
        "cal_no_title": "Brak tytułu",
        "cal_title": "Kalendarz",
        "cal_monthly_title": "Kalendarz Miesięczny",
        "weather_no_forecast": "Brak prognozy",
        "weather_title": "Pogoda",
        "weather_feels": "Odczuwalna",
        "weather_wind": "Wiatr",
        "weather_pressure": "Ciśnienie",
        "weather_humidity": "Wilgotność",
        "weather_no_daily": "Brak prognozy dziennej.",
        "weather_graph_err": "Błąd generowania wykresu",
        "forecast_24h": "Prognoza 24h",
    },
    "de": {
        "todo_no_tasks": "Keine Aufgaben auf der Liste",
        "todo_no_description": "Keine Beschreibung",
        "rss_failed": "RSS-Feed konnte nicht geladen werden",
        "rss_prev": "Zurück",
        "rss_next": "Weiter",
        "rss_page": "Seite",
        "rss_no_title": "Ohne Titel",
        "energy_title": "Energiepanel",
        "energy_live": "Aktuelle Leistung",
        "energy_solar": "Solar",
        "energy_import": "Netzbezug",
        "energy_export": "Netzeinspeisung",
        "energy_consumption": "Verbrauch",
        "energy_net": "Nettosaldo",
        "energy_self": "Autarkie",
        "crypto_title": "Krypto",
        "crypto_updated": "Aktualisiert",
        "crypto_no_chart": "Keine Diagrammdaten",
        "fx_default_title": "Wechselkurse",
        "fx_no_hist": "Keine Verl.",
        "cal_no_events": "Keine Termine an diesem Tag",
        "cal_no_title": "Ohne Titel",
        "cal_title": "Kalender",
        "cal_monthly_title": "Monatskalender",
        "weather_no_forecast": "Keine Vorhersage",
        "weather_title": "Wetter",
        "weather_feels": "Gefühlt",
        "weather_wind": "Wind",
        "weather_pressure": "Luftdruck",
        "weather_humidity": "Luftfeuchtigkeit",
        "weather_no_daily": "Keine Tagesvorhersage.",
        "weather_graph_err": "Diagrammfehler",
        "forecast_24h": "24h-Vorhersage",
    },
    "fr": {
        "todo_no_tasks": "Aucune tâche dans la liste",
        "todo_no_description": "Pas de description",
        "rss_failed": "Impossible de charger le flux RSS",
        "rss_prev": "Précédent",
        "rss_next": "Suivant",
        "rss_page": "Page",
        "rss_no_title": "Sans titre",
        "energy_title": "Panneau énergie",
        "energy_live": "Puissance actuelle",
        "energy_solar": "Solaire",
        "energy_import": "Import réseau",
        "energy_export": "Export réseau",
        "energy_consumption": "Consommation",
        "energy_net": "Solde net",
        "energy_self": "Autarcie",
        "crypto_title": "Crypto",
        "crypto_updated": "Mis à jour",
        "crypto_no_chart": "Pas de graphique",
        "fx_default_title": "Taux de change",
        "fx_no_hist": "Pas d’hist.",
        "cal_no_events": "Aucun événement ce jour",
        "cal_no_title": "Sans titre",
        "cal_title": "Calendrier",
        "cal_monthly_title": "Calendrier mensuel",
        "weather_no_forecast": "Pas de prévision",
        "weather_title": "Météo",
        "weather_feels": "Ressenti",
        "weather_wind": "Vent",
        "weather_pressure": "Pression",
        "weather_humidity": "Humidité",
        "weather_no_daily": "Pas de prévision journalière.",
        "weather_graph_err": "Erreur du graphique",
        "forecast_24h": "Prévision 24 h",
    },
    "es": {
        "todo_no_tasks": "No hay tareas en la lista",
        "todo_no_description": "Sin descripción",
        "rss_failed": "No se pudo cargar el canal RSS",
        "rss_prev": "Anterior",
        "rss_next": "Siguiente",
        "rss_page": "Página",
        "rss_no_title": "Sin título",
        "energy_title": "Panel energético",
        "energy_live": "Potencia actual",
        "energy_solar": "Solar",
        "energy_import": "Importación red",
        "energy_export": "Exportación red",
        "energy_consumption": "Consumo",
        "energy_net": "Balance neto",
        "energy_self": "Autoconsumo",
        "crypto_title": "Cripto",
        "crypto_updated": "Actualizado",
        "crypto_no_chart": "Sin datos del gráfico",
        "fx_default_title": "Tipos de cambio",
        "fx_no_hist": "Sin hist.",
        "cal_no_events": "No hay eventos este día",
        "cal_no_title": "Sin título",
        "cal_title": "Calendario",
        "cal_monthly_title": "Calendario mensual",
        "weather_no_forecast": "Sin previsión",
        "weather_title": "Tiempo",
        "weather_feels": "Sensación",
        "weather_wind": "Viento",
        "weather_pressure": "Presión",
        "weather_humidity": "Humedad",
        "weather_no_daily": "Sin previsión diaria.",
        "weather_graph_err": "Error al generar el gráfico",
        "forecast_24h": "Previsión 24 h",
    },
    "nl": {
        "todo_no_tasks": "Geen taken op de lijst",
        "todo_no_description": "Geen beschrijving",
        "rss_failed": "RSS-feed laden mislukt",
        "rss_prev": "Vorige",
        "rss_next": "Volgende",
        "rss_page": "Pagina",
        "rss_no_title": "Geen titel",
        "energy_title": "Energiepaneel",
        "energy_live": "Actueel vermogen",
        "energy_solar": "Zonne-energie",
        "energy_import": "Import net",
        "energy_export": "Export net",
        "energy_consumption": "Verbruik",
        "energy_net": "Netsaldo",
        "energy_self": "Zelfvoorz.",
        "crypto_title": "Crypto",
        "crypto_updated": "Bijgewerkt",
        "crypto_no_chart": "Geen grafiekgegevens",
        "fx_default_title": "Wisselkoersen",
        "fx_no_hist": "Geen gesch.",
        "cal_no_events": "Geen afspraken deze dag",
        "cal_no_title": "Geen titel",
        "cal_title": "Agenda",
        "cal_monthly_title": "Maandkalender",
        "weather_no_forecast": "Geen voorspelling",
        "weather_title": "Weer",
        "weather_feels": "Voelt als",
        "weather_wind": "Wind",
        "weather_pressure": "Druk",
        "weather_humidity": "Vochtigheid",
        "weather_no_daily": "Geen dagvoorspelling.",
        "weather_graph_err": "Grafiekfout",
        "forecast_24h": "24 uur voorspelling",
    },
    "cs": {
        "todo_no_tasks": "Seznam nemá žádné úkoly",
        "todo_no_description": "Bez popisu",
        "rss_failed": "RSS kanál se nepodařilo načíst",
        "rss_prev": "Předchozí",
        "rss_next": "Další",
        "rss_page": "Strana",
        "rss_no_title": "Bez názvu",
        "energy_title": "Energetický panel",
        "energy_live": "Aktuální výkon",
        "energy_solar": "Solární",
        "energy_import": "Odběr ze sítě",
        "energy_export": "Dodávka do sítě",
        "energy_consumption": "Spotřeba",
        "energy_net": "Čistá bilance",
        "energy_self": "Soběst.",
        "crypto_title": "Krypto",
        "crypto_updated": "Aktualizováno",
        "crypto_no_chart": "Žádná data grafu",
        "fx_default_title": "Směnné kurzy",
        "fx_no_hist": "Bez hist.",
        "cal_no_events": "Tento den žádné události",
        "cal_no_title": "Bez názvu",
        "cal_title": "Kalendář",
        "cal_monthly_title": "Měsíční kalendář",
        "weather_no_forecast": "Bez předpovědi",
        "weather_title": "Počasí",
        "weather_feels": "Pocitově",
        "weather_wind": "Vítr",
        "weather_pressure": "Tlak",
        "weather_humidity": "Vlhkost",
        "weather_no_daily": "Žádná denní předpověď.",
        "weather_graph_err": "Chyba grafu",
        "forecast_24h": "Předpověď 24 h",
    },
}


def tr(lang: str, key: str) -> str:
    L = normalize_lang(lang)
    row = _STR.get(L) or _STR["en"]
    return row.get(key) or _STR["en"][key]


# --- HA state labels for status panel ---
_STATE_MAPS: dict[str, dict[str, str]] = {
    "en": {
        "on": "On", "off": "Off", "open": "Open", "closed": "Closed",
        "home": "Home", "not_home": "Away", "locked": "Locked", "unlocked": "Unlocked",
        "unavailable": "Unavailable", "unknown": "Unknown",
    },
    "pl": {
        "on": "Włączone", "off": "Wyłączone", "open": "Otwarte", "closed": "Zamknięte",
        "home": "w Domu", "not_home": "Poza domem", "locked": "Zamknięte", "unlocked": "Otwarte",
        "unavailable": "Niedostępny", "unknown": "Nieznany",
    },
    "de": {
        "on": "An", "off": "Aus", "open": "Offen", "closed": "Geschlossen",
        "home": "Zu Hause", "not_home": "Abwesend", "locked": "Gesperrt", "unlocked": "Entsperrt",
        "unavailable": "Nicht verfügbar", "unknown": "Unbekannt",
    },
    "fr": {
        "on": "Marche", "off": "Arrêt", "open": "Ouvert", "closed": "Fermé",
        "home": "Présent", "not_home": "Absent", "locked": "Verrouillé", "unlocked": "Déverrouillé",
        "unavailable": "Indisponible", "unknown": "Inconnu",
    },
    "es": {
        "on": "Encendido", "off": "Apagado", "open": "Abierto", "closed": "Cerrado",
        "home": "En casa", "not_home": "Fuera", "locked": "Bloqueado", "unlocked": "Desbloqueado",
        "unavailable": "No disponible", "unknown": "Desconocido",
    },
    "nl": {
        "on": "Aan", "off": "Uit", "open": "Open", "closed": "Gesloten",
        "home": "Thuis", "not_home": "Afwezig", "locked": "Vergrendeld", "unlocked": "Ontgrendeld",
        "unavailable": "Niet beschikbaar", "unknown": "Onbekend",
    },
    "cs": {
        "on": "Zapnuto", "off": "Vypnuto", "open": "Otevřeno", "closed": "Zavřeno",
        "home": "Doma", "not_home": "Pryč", "locked": "Zamčeno", "unlocked": "Odemčeno",
        "unavailable": "Nedostupné", "unknown": "Neznámé",
    },
}


def state_translations(lang: str) -> dict[str, str]:
    L = normalize_lang(lang)
    return dict(_STATE_MAPS.get(L) or _STATE_MAPS["en"])


def wind_direction_labels(lang: str) -> list[str]:
    """8-point compass; Polish uses Polish abbreviations."""
    if normalize_lang(lang) == "pl":
        return ["Pn", "Pn-Wsch", "Wsch", "Pd-Wsch", "Pd", "Pd-Zach", "Zach", "Pn-Zach"]
    return ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]
