# Describes services available for the Visionect Joan integration.

set_url:
  name: Set URL
  description: Changes the URL displayed on the device screen.
  fields:
    device_id:
      name: Device
      description: The Visionect device to perform the action on.
      required: true
      selector:
        device:
          integration: visionect_joan
    url:
      name: URL
      description: New URL for display or local photo address.
      required: true
      example: "URL (https://www.google.com) / local photo address (http://ipHA:8123/local/photo.png) "
      selector:
        text:
    use_web:
      name: Use Web Interface
      description: Whether to use web interface (currently not functional - kept for future use).
      required: false
      default: false
      selector:
        boolean:

send_text:
  name: Send Text Message
  description: Sends a text message optimized for e-ink display.
  fields:
    device_id:
      name: Device
      description: The Visionect e-ink device to send the message to.
      required: true
      selector:
        device:
          integration: visionect_joan
    message:
      name: Message
      description: The text message to display on the e-ink screen.
      required: true
      example: "Spotkanie o 14:00"
      selector:
        text:
          multiline: true
    text_color:
      name: Text Color
      description: Color of the text (black or white for e-ink).
      required: false
      default: "black"
      selector:
        select:
          options:
            - label: "Czarny"
              value: "black"
            - label: "Biały"
              value: "white"
    background_color:
      name: Background Color
      description: Background color of the e-ink screen.
      required: false
      default: "white"
      selector:
        select:
          options:
            - label: "Biały"
              value: "white"
            - label: "Czarny"
              value: "black"
    text_size:
      name: Text Size
      description: Size of the text (recommended 24px-36px for e-ink).
      required: false
      default: "28px"
      example: "32px"
      selector:
        text:
    text_align:
      name: Text Alignment
      description: Text alignment on the screen.
      required: false
      default: "center"
      selector:
        select:
          options:
            - label: "Do lewej"
              value: "left"
            - label: "Wyśrodkowany"
              value: "center"
            - label: "Do prawej"
              value: "right"
    font_family:
      name: Font Family
      description: Font family optimized for e-ink readability.
      required: false
      default: "Arial, Helvetica, sans-serif"
      selector:
        select:
          options:
            - label: "Arial - Standardowa, bardzo czytelna"
              value: "Arial, Helvetica, sans-serif"
            - label: "Georgia - Elegancka z szerokimi literami"
              value: "Georgia, 'Times New Roman', serif"
            - label: "Verdana - Szeroka i bardzo czytelna"
              value: "Verdana, Geneva, sans-serif"
            - label: "Tahoma - Kompaktowa ale czytelna"
              value: "Tahoma, Geneva, sans-serif"
            - label: "Trebuchet MS - Nowoczesna zaokrąglona"
              value: "'Trebuchet MS', Helvetica, sans-serif"
            - label: "Lucida Grande - Okrągła i przyjazna"
              value: "'Lucida Grande', 'Lucida Sans Unicode', sans-serif"
            - label: "Palatino - Klasyczna książkowa"
              value: "Palatino, 'Palatino Linotype', serif"
            - label: "Courier New - Jednakowa szerokość znaków"
              value: "'Courier New', Courier, monospace"
            - label: "Franklin Gothic - Pogrubiona wyrazista"
              value: "'Franklin Gothic Medium', Arial, sans-serif"
            - label: "Garamond - Staroclasyczna elegancka"
              value: "Garamond, 'Times New Roman', serif"