# Describes services available for the Visionect Joan integration.

set_url:
  name: Set URL
  description: Changes the URL displayed on the device screen.
  fields:
    device_id:
      name: Device
      description: The Visionect device to perform the action on.
      required: true
      selector:
        device:
          integration: visionect_joan
    url:
      name: URL
      description: The new URL to display.
      required: true
      example: "https://www.home-assistant.io"
      selector:
        text:

send_text:
  name: Send Text Message
  description: Sends a text message optimized for e-ink display.
  fields:
    device_id:
      name: Device
      description: The Visionect e-ink device to send the message to.
      required: true
      selector:
        device:
          integration: visionect_joan
    message:
      name: Message
      description: The text message to display on the e-ink screen.
      required: true
      example: "Meeting at 2:00 PM in the conference room"
      selector:
        text:
          multiline: true
    text_color:
      name: Text Color
      description: Color of the text (black or white for e-ink).
      required: false
      default: "black"
      selector:
        select:
          options:
            - label: "Black"
              value: "black"
            - label: "White"
              value: "white"
    background_color:
      name: Background Color
      description: Background color of the e-ink screen.
      required: false
      default: "white"
      selector:
        select:
          options:
            - label: "White"
              value: "white"
            - label: "Black"
              value: "black"
    text_size:
      name: Text Size
      description: Size of the text (e.g., 28px).
      required: false
      default: "28px"
      example: "32px"
      selector:
        text:
    text_align:
      name: Text Alignment
      description: Text alignment on the screen.
      required: false
      default: "center"
      selector:
        select:
          options:
            - label: "Left"
              value: "left"
            - label: "Center"
              value: "center"
            - label: "Right"
              value: "right"
    font_family:
      name: Font Family
      description: Font family optimized for e-ink readability.
      required: false
      default: "Arial, Helvetica, sans-serif"
      selector:
        select:
          options:
            - "Arial, Helvetica, sans-serif"
            - "Georgia, 'Times New Roman', serif"
            - "Verdana, Geneva, sans-serif"
            - "Tahoma, Geneva, sans-serif"
            - "'Trebuchet MS', Helvetica, sans-serif"
            - "'Lucida Grande', 'Lucida Sans Unicode', sans-serif"
            - "Palatino, 'Palatino Linotype', serif"
            - "'Courier New', Courier, monospace"
            - "'Franklin Gothic Medium', Arial, sans-serif"
            - "Garamond, 'Times New Roman', serif"
    font_weight:
      name: Font Weight
      description: Sets the weight (thickness) of the font.
      required: false
      default: "normal"
      selector:
        select:
          options:
            - label: "Normal"
              value: "normal"
            - label: "Bold"
              value: "bold"

set_display_rotation:
  name: Set Display Rotation
  description: Changes the display rotation of the Joan tablet screen.
  fields:
    device_id:
      name: Device
      description: The Joan device to change display rotation for.
      required: true
      selector:
        device:
          integration: visionect_joan
    display_rotation:
      name: Display Rotation
      description: The display rotation to set on the Joan tablet.
      required: true
      selector:
        select:
          options:
            - label: "Landscape"
              value: "0"
            - label: "Portrait, 90°"
              value: "1"
            - label: "Landscape, 180°"
              value: "2"
            - label: "Portrait, 270°"
              value: "3"