# custom_components/visionect_joan/services.yaml

set_url:
  name: Set URL
  description: >-
    Changes the URL displayed on the device screen.
    This can be an internet address or a local URL to display an image from Home Assistant.
  fields:
    device_id:
      name: Device
      description: The Visionect device to perform the action on.
      required: true
      selector:
        device:
          integration: visionect_joan
    url:
      name: URL
      description: >-
        The new URL to display. 
        To show a local image, place it in your `\\<HA_ADDRESS>\config\www` folder (e.g., `photo.png`) and use the URL `http://<address_ip_ha>:8123/local/photo.png`.
        The `www` folder is accessible via Samba. If you already have an Appdaemon installed in Home Assistant, then the address to your Dashboard will be http://<address_ip_ha>:5050/<name_dashboard>
      
      required: true
      example: "http://192.168.xxx.xxx:8123/local/my_dashboard.png"
      selector:
        text:

send_text:
  name: Send Text Message
  description: Sends a text message, optionally with an image, optimized for e-ink display.
  fields:
    device_id:
      name: Device
      description: The Visionect e-ink device to send the message to.
      required: true
      selector:
        device:
          integration: visionect_joan
    message:
      name: Message
      description: The text message to display on the e-ink screen.
      required: true
      example: "Meeting at 2:00 PM in the conference room"
      selector:
        text:
          multiline: true
    # ---> ZMIANA: Dodano nową opcję do wyboru <---
    layout:
      name: Layout
      description: Arrangement of text and image on the screen.
      required: false
      default: "text_only"
      selector:
        select:
          options:
            - label: "Text Only"
              value: "text_only"
            - label: "Image Above Text"
              value: "image_top"
            - label: "Image Below Text"
              value: "image_bottom"
            - label: "Image to the Left of Text"
              value: "image_left"
            - label: "Image to the Right of Text"
              value: "image_right"
    image_url:
      name: Image URL
      description: >-
        URL of the image to display. Optional.
        For local images, use the format `http://<YOUR_HA_IP>:8123/local/image.png`.
      required: false
      example: "http://192.168.1.100:8123/local/icons/weather.png"
      selector:
        text:
    text_color:
      name: Text Color
      description: Color of the text (black or white for e-ink).
      required: false
      default: "black"
      selector:
        select:
          options:
            - label: "Black"
              value: "black"
            - label: "White"
              value: "white"
    background_color:
      name: Background Color
      description: Background color of the e-ink screen.
      required: false
      default: "white"
      selector:
        select:
          options:
            - label: "White"
              value: "white"
            - label: "Black"
              value: "black"
    text_size:
      name: Text Size
      description: Size of the text in pixels.
      required: false
      default: 28
      example: 32
      selector:
        number:
          min: 10
          max: 150
          step: 1
          mode: slider
          unit_of_measurement: "px"
    text_align:
      name: Text Alignment
      description: Text alignment on the screen.
      required: false
      default: "center"
      selector:
        select:
          options:
            - label: "Left"
              value: "left"
            - label: "Center"
              value: "center"
            - label: "Right"
              value: "right"
    font_family:
      name: Font Family
      description: Themed font family for e-ink readability.
      required: false
      default: "Nowoczesna"
      selector:
        select:
          options:
            - label: "Nowoczesna"
              value: "Nowoczesna"
            - label: "Czytelna"
              value: "Czytelna"
            - label: "Archivo Black"
              value: "Archivo Black"
            - label: "Arbutus"
              value: "Arbutus"
            - label: "Asimovian"
              value: "Asimovian"
            - label: "Bangers"
              value: "Bangers"
            - label: "Blaka"
              value: "Blaka"
            - label: "Bungee"
              value: "Bungee"
            - label: "Bungee Shade"
              value: "Bungee Shade"
            - label: "Cherry Bomb One"
              value: "Cherry Bomb One"
            - label: "Cinzel Decorative"
              value: "Cinzel Decorative"
            - label: "Damion"
              value: "Damion"
            - label: "Diplomata SC"
              value: "Diplomata SC"
            - label: "Fascinate"
              value: "Fascinate"
            - label: "Joti One"
              value: "Joti One"
            - label: "Libertinus Keyboard"
              value: "Libertinus Keyboard"
            - label: "MedievalSharp"
              value: "MedievalSharp"
            - label: "Michroma"
              value: "Michroma"
            - label: "New Rocker"
              value: "New Rocker"
            - label: "Rubik Wet Paint"
              value: "Rubik Wet Paint"
            - label: "Spicy Rice"
              value: "Spicy Rice"
            - label: "Story Script"
              value: "Story Script"
    font_weight:
      name: Font Weight
      description: Sets the weight (thickness) of the font.
      required: false
      default: "normal"
      selector:
        select:
          options:
            - label: "Normal"
              value: "normal"
            - label: "Bold"
              value: "bold"

set_display_rotation:
  name: Set Display Rotation
  description: Changes the display rotation of the Joan tablet screen.
  fields:
    device_id:
      name: Device
      description: The Joan device to change display rotation for.
      required: true
      selector:
        device:
          integration: visionect_joan
    display_rotation:
      name: Display Rotation
      description: The display rotation to set on the Joan tablet.
      required: true
      selector:
        select:
          options:
            - label: "Landscape"
              value: "0"
            - label: "Portrait, 90°"
              value: "1"
            - label: "Landscape, 180°"
              value: "2"
            - label: "Portrait, 270°"
              value: "3"

force_refresh:
  name: Force Refresh
  description: Forces the device to immediately reload and display the content from its currently configured URL.
  fields:
    device_id:
      name: Device
      description: The Visionect device to refresh.
      required: true
      selector:
        device:
          integration: visionect_joan

clear_display:
  name: Clear Display
  description: Clears the device's e-ink screen, typically to a white screen.
  fields:
    device_id:
      name: Device
      description: The Visionect device to clear.
      required: true
      selector:
        device:
          integration: visionect_joan